--- 
title: "Data Science Workshop"
subtitle: "British Society for Proteomic Research Meeting 2018"
author: "Alistair Bailey"
date: "`r format(Sys.Date(),format='%B %d %Y')`"
output: 
  bookdown::gitbook: default
  bookdown::epub_book: default
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
    keep_tex: yes
    citation_package: natbib
    latex_engine: xelatex
documentclass: book
fontsize: 12pt
linestretch: 1.5
toc-depth: 1
secnumdepth: 1
lof: FALSE
lot: FALSE
site: bookdown::bookdown_site
bibliography: [packages.bib, book.bib]
biblio-style: apalike
link-citations: yes
#geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
description: "Lessons for the BSPR 2018 Data Science Workshop"
---

```{r include=FALSE}
library(tidyverse)
library(janitor)
library(cowplot)
#library(VennDiagram)
#library(gridExtra)
#library(cowplot)
# automatically create a bib database for R packages
knitr::write_bib(c(.packages(), 'bookdown', 'knitr', 'rmarkdown'), 'packages.bib')

options(knitr.graphics.auto_pdf = TRUE)
```

# Overview {-}

These lessons cover:

1. An introduction to R and RStudio
2. An introduction to the tidyverse
3. Importing and transforming proteomics data
4. Visualisation of proteomics analysis

## Requirements {-}

Up to date version of R and Rstudio

The following R packages:

```{r packages, eval=FALSE}
install.packages(c("tidyverse","janitor","gplots","pheatmap"))
```



